# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yaml
name: viclara-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # conda-forge packages, sorting now alphabetically, without the channel prefix!
  - matplotlib=3.0.3        # Current 3.1.0 build incompatible with multiqc=1.7
  - r-base=3.6.1
  # - conda-forge::r-repo=2.1.5
  # - conda-forge::r-biocmanager=1.30.10
  - conda-forge::r-data.table=1.12.4
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=1.1
  # - conda-forge::r-ggplot2=3.1.0
  # - conda-forge::r-cairo
  # - conda-forge::r-pheatmap=1.0.10
  # - conda-forge::r-dplyr=1.0.1
  # - conda-forge::r-reshape2=1.4.4
  # - conda-forge::r-svglite=1.2.3.2
  # - conda-forge::r-cowplot=0.9.3
  # - conda-forge::r-gridextra=2.3
  - conda-forge::pandas=1.0.5

  ## bioconda packages, see above
  - fastqc=0.11.8
  - trimmomatic=0.38
  - bbmap=38.67
  - multiqc=1.7
  - samtools=1.9
  - bwa=0.7.17
  - bowtie2=2.2.5
  - kraken2=2.0.9